[toolchain]
package_manager = "yarn"
anchor_version = "0.32.1"
solana_version = "2.3.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
priven = "EMqLDAtqv5QPpBDk4fQtFDps7cXeWp1goNbra8fNWXaM"

[programs.devnet]
priven = "EMqLDAtqv5QPpBDk4fQtFDps7cXeWp1goNbra8fNWXaM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

# QuickNode RPC endpoint for devnet
[provider.devnet]
cluster = "https://prettiest-withered-dew.solana-devnet.quiknode.pro/REDACTED_TOKEN/"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
